from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
driver.implicitly_wait(3)
driver.execute_script("window.scrollBy(0, 600);")
ruby = driver.find_element_by_xpath('//*[@id="text-22-sub_row_1-0-2-0-0"]/div/ul/li/a[1]/h3')
ruby.click()
reviews = driver.find_element_by_css_selector('[href="#tab-reviews"]')
reviews.click()
star = driver.find_element_by_class_name("star-5")
star.click()
review = driver.find_element_by_id("comment")
review.send_keys("Nice book!")
name = driver.find_element_by_id("author")
name.send_keys("Irina")
email = driver.find_element_by_id("email")
email.send_keys("test@test.ru")
submit = driver.find_element_by_id("submit")
submit.click()
driver.quit()
